In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_excel('Análisis_de_Piso.xlsx')
data.head(10)

,Unnamed: 0,Leads Piso 2024,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 41,Unnamed: 42,979,811,Unnamed: 45,Unnamed: 46,Factor minimo mejor vendedor,Factor minimo mejor vendedor .1,Unnamed: 49,Unnamed: 50
0,NaN,459,27,95,110,65,107,88,59,40,...,RAKING VENTAS,Dependencia de Piso,Historico de PDM,Historico de SDC,Conversion PDM,Conversion SDC,Factor PDM,Factor SDC,Raking PDM,Raking SDC
1,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ABIGAIL,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0,1,5,1,0,1.00,5.00,1,20
3,ALAN GONZALES,1,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40,0.31,0.02,3.28,2.22,7,10
4,ALICIA LEDESMA,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,1,1,0,0,0.00,0.00,NaN,NaN
5,AURELIO FELIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6,...,11,0.38,28,31,0.29,0.01,3.50,3.88,9,18
6,CARLOS ALBERTO NIETO,NaN,NaN,NaN,2,NaN,NaN,2,8,4,...,8,0.6,64,30,0.23,0.02,4.27,2.00,13,7
7,CARLOS TEXIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,...,17,0.25,21,26,0.19,0.01,5.25,6.50,18,23
8,CARLOS MANUEL CARMONA,18,10,27,34,11,3,NaN,NaN,NaN,...,0,0,54,8,0,0,0.00,0.00,NaN,NaN
9,CINTYA,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,...,0,0,3,5,0,0,0.00,0.00,NaN,NaN

In [3]:
data= pd.read_excel('Análisis_de_Piso.xlsx', skiprows=2)
data

,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,...,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,ABIGAIL,23.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0.00,1,5.0,1.00,0.00,1.00,5.00,1.0,20.0
1,ALAN GONZALES,1.0,NaN,NaN,NaN,NaN,NaN,NaN,,NaN,...,6,0.61,59,40.0,0.31,0.02,3.28,2.22,7.0,10.0
2,ALICIA LEDESMA,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0.00,1,1.0,0.00,0.00,0.00,0.00,NaN,NaN
3,AURELIO FELIPE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,6.0,...,11,0.38,28,31.0,0.29,0.01,3.50,3.88,9.0,18.0
4,CARLOS ALBERTO NIETO,NaN,NaN,NaN,2.0,NaN,NaN,2.0,8,4.0,...,8,0.60,64,30.0,0.23,0.02,4.27,2.00,13.0,7.0
5,CARLOS TEXIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,17,0.25,21,26.0,0.19,0.01,5.25,6.50,18.0,23.0
6,CARLOS MANUEL CARMONA,18.0,10.0,27.0,34.0,11.0,3.0,NaN,NaN,NaN,...,0,0.00,54,8.0,0.00,0.00,0.00,0.00,NaN,NaN
7,CINTYA,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,0,0.00,3,5.0,0.00,0.00,0.00,0.00,NaN,NaN
8,CLAUDIA GALVAN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19,0.00,25,22.0,0.08,0.00,12.50,11.00,22.0,26.0
9,CASA,1.0,NaN,3.0,3.0,2.0,NaN,NaN,NaN,NaN,...,4,0.10,20,32.0,1.05,0.00,0.95,1.52,NaN,3.0
10,DANIEL DE LEON CANDIA,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1,5.0,...,9,0.42,36,25.0,0.33,0.02,3.00,2.08,6.0,9.0
11,DAVID JIMENEZ,NaN,NaN,10.0,5.0,7.0,NaN,NaN,NaN,NaN,...,23,0.00,19,5.0,0.05,0.00,19.00,5.00,23.0,20.0
12,Demo Vendedor,2.0,2.0,2.0,NaN,NaN,3.0,NaN,NaN,NaN,...,-,0.00,7,5.0,0.00,0.00,0.00,0.00,NaN,NaN
13,GUADALUPE PEREZ,NaN,NaN,1.0,2.0,5.0,NaN,NaN,NaN,NaN,...,-,0.00,8,7.0,0.00,0.00,0.00,0.00,NaN,NaN
14,SEBASTIAN BENHUMEA,1.0,NaN,1.0,NaN,NaN,1.0,1.0,NaN,NaN,...,19,0.00,25,22.0,0.08,0.00,12.50,11.00,22.0,26.0
15,USUARIO DE BDC Y CASA,2.0,1.0,4.0,1.0,NaN,3.0,6.0,1,NaN,...,10,0.00,17,11.0,0.65,0.00,1.55,1.00,3.0,1.0
16,JAIME GONZALEZ,NaN,NaN,1.0,1.0,4.0,12.0,29.0,8,7.0,...,3,0.28,34,61.0,0.74,0.00,1.36,2.44,2.0,12.0
17,JESUS SERRANO,114.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19,1.00,18,6.0,0.11,0.17,9.00,3.00,20.0,15.0
18,JOSE CARLOS ZENTENO,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,...,23,1.00,5,2.0,0.20,0.50,5.00,2.00,17.0,7.0
19,JOSE EDUARDO PARADA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,4,8.0,0.00,0.00,0.00,0.00,NaN,NaN
20,JOSE MANUEL LOPEZ,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,18,0.67,1,5.0,3.00,0.13,0.33,1.67,NaN,4.0
21,JOSE MANUEL LOPEZ,67.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,0,7.0,NaN,0.00,0.00,0.00,NaN,NaN
22,JOSETTE RAMON,NaN,NaN,NaN,2.0,5.0,17.0,5.0,9,NaN,...,7,0.38,48,49.0,0.33,0.01,3.00,3.06,6.0,16.0
23,LAURA LOPEZ,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,-,0.00,3,2.0,0.00,0.00,0.00,0.00,NaN,NaN
24,LIZBETH GOMEZ GONZALEZ,10.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,4,3.0,0.00,0.00,0.00,0.00,NaN,NaN
25,LUIS ALBERTO RODRIGUEZ,6.0,NaN,12.0,NaN,NaN,2.0,NaN,NaN,NaN,...,-,0.00,3,5.0,0.00,0.00,0.00,0.00,NaN,NaN
26,LUISA LBERTO GOMEZ,42.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,19,0.50,9,4.0,0.22,0.13,4.50,2.00,14.0,7.0
27,MARIA GUADALUPE PALACIOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,13,0.43,35,24.0,0.20,0.02,5.00,3.43,17.0,17.0
28,MAURICIO ALFREDO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11,0.50,29,42.0,0.28,0.01,3.63,5.25,10.0,21.0
29,MIGUEL ANGEL SONDEREGGER,37.0,NaN,4.0,36.0,21.0,37.0,25.0,16,8.0,...,2,0.64,117,66.0,0.24,0.01,4.18,2.36,12.0,11.0
30,MONICA GISELA FLORES,NaN,NaN,NaN,NaN,NaN,2.0,7.0,5,2.0,...,-,0.00,22,9.0,0.00,0.00,0.00,0.00,NaN,NaN
31,NANCY OLASCOAGA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2,5.0,...,14,0.00,48,55.0,0.13,0.00,8.00,9.17,19.0,24.0
32,NAYELI MONTES DEOCA,41.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,23,0.00,4,3.0,0.25,0.00,4.00,3.00,11.0,15.0
33,OSCAR ALONSO,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,14,0.00,29,36.0,0.21,0.00,4.83,6.00,15.0,22.0
34,PAUL ROSAS IRIGOYIN,1.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,14,0.83,5,9.0,1.20,0.09,0.83,1.50,NaN,2.0
35,PAUL ROSAS,83.0,7.0,11.0,6.0,NaN,NaN,NaN,NaN,NaN,...,-,0.00,1,6.0,0.00,0.00,0.00,0.00,NaN,NaN
36,PEDRO GONZALES,2.0,NaN,11.0,17.0,7.0,19.0,11.0,5,2.0,...,1,0.39,123,75.0,0.29,0.01,3.42,2.08,8.0,9.0
37,RICARDO SILVA HERAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-,0.00,3,2.0,0.00,0.00,0.00,0.00,NaN,NaN
38,sys_competition,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,...,-,0.00,0,NaN,NaN,NaN,0.00,0.00,NaN,NaN
39,VICTOR MANUEL SANCHEZ ARROYO,4.0,3.0,NaN,1.0,2.0,NaN,NaN,2,NaN,...,4,0.14,46,57.0,0.46,0.00,2.19,2.71,4.0,13.0

In [8]:
data.isnull().sum()[data.isnull().sum() > 0]

feb            19
mar            31
abr            23
may            28
jun            30
jul            29
ago            30
sep            27
oct            31
nov            25
dic            31
ene            30
feb.1          30
mar.1          33
abr.1          31
mar.2          38
abr.2          35
may.1          39
jun.1          38
jul.1          36
ago.1          36
sep.1          35
oct.1          38
nov.1          34
dic.1          34
ene.1          35
feb.3          33
mar.3          35
may.2          34
jun.2          38
Unnamed: 40    14
Unnamed: 44     1
Unnamed: 45     2
Unnamed: 46     1
Unnamed: 49    17
Unnamed: 50    14
dtype: int64

In [9]:
data2 = data.copy()

In [10]:
data2.columns.values[35] = 'may.2'

In [11]:
data2[['feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic','ene']] = data2[['feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic','ene']].fillna(0)

In [13]:
data2[['feb.1', 'mar.1', 'abr.1', 'may.1', 'jun.1', 'jul.1', 'ago.1', 'sep.1', 'oct.1', 'nov.1', 'dic.1','ene.1']] = data2[['feb.1', 'mar.1', 'abr.1', 'may.1', 'jun.1', 'jul.1', 'ago.1', 'sep.1', 'oct.1', 'nov.1', 'dic.1','ene.1']].fillna(0)

In [22]:
data2[['feb.2','mar.2','abr.2','may.2','jun.2']] = data2[['feb.2','mar.2','abr.2','may.2','jun.2']].fillna(0)

In [24]:
data2[['feb.3','mar.3']] = data2[['feb.3','mar.3']].fillna(0)

In [25]:
data2.isnull().sum()[data2.isnull().sum() > 0]

Unnamed: 40    14
Unnamed: 44     1
Unnamed: 45     2
Unnamed: 46     1
Unnamed: 49    17
Unnamed: 50    14
dtype: int64

In [26]:
data2[['Unnamed: 40','Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 49', 'Unnamed: 50']] = data2[['Unnamed: 40','Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 49', 'Unnamed: 50']].fillna(0)

In [34]:
pd.options.display.max_columns = None
data2.head(10)

,Asesor,feb,mar,abr,may,jun,jul,ago,sep,oct,nov,dic,ene,feb.1,mar.1,abr.1,,.1,Unnamed: 18,Unnamed: 19,feb.2,mar.2,abr.2,may.1,jun.1,jul.1,ago.1,sep.1,oct.1,nov.1,dic.1,ene.1,feb.3,mar.3,abr.3,may.2,jun.2,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50
0,ABIGAIL,23.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23,0,17,28,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0,0,0.00,1.0,23,0.00,1,5.0,1.00,0.00,1.00,5.00,1.0,20.0
1,ALAN GONZALES,1.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,1.0,9.0,15.0,12.0,19.0,5.0,62,61,8,3,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,4.0,1.0,2.0,1,1.0,0.0,10,11,0.18,18.0,6,0.61,59,40.0,0.31,0.02,3.28,2.22,7.0,10.0
2,ALICIA LEDESMA,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,38,28,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,0,0,0.00,0.0,0,0.00,1,1.0,0.00,0.00,0.00,0.00,0.0,0.0
3,AURELIO FELIPE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,6.0,0.0,0.0,0.0,0.0,20.0,6.0,33,33,14,8,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,,3.0,2.0,8,3,0.09,8.0,11,0.38,28,31.0,0.29,0.01,3.50,3.88,9.0,18.0
4,CARLOS ALBERTO NIETO,0.0,0.0,0.0,2.0,0.0,0.0,2.0,8,4.0,10.0,11.0,7.0,13.0,0.0,0.0,57,55,9,5,,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,1.0,0.0,3.0,0.0,,0.0,0.0,7,9,0.16,15.0,8,0.60,64,30.0,0.23,0.02,4.27,2.00,13.0,7.0
5,CARLOS TEXIS,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,4,4,32,17,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,,0.0,0.0,1,1,0.25,4.0,17,0.25,21,26.0,0.19,0.01,5.25,6.50,18.0,23.0
6,CARLOS MANUEL CARMONA,18.0,10.0,27.0,34.0,11.0,3.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,103,3,5,21,,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,16,6,0.06,0.0,0,0.00,54,8.0,0.00,0.00,0.00,0.00,0.0,0.0
7,CINTYA,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,38,28,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,1,0,0.00,0.0,0,0.00,3,5.0,0.00,0.00,0.00,0.00,0.0,0.0
8,CLAUDIA GALVAN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,3,3,34,21,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,,0.0,0.0,2,0,0.00,2.0,19,0.00,25,22.0,0.08,0.00,12.50,11.00,22.0,26.0
9,CASA,1.0,0.0,3.0,3.0,2.0,0.0,0.0,0,0.0,1.0,0.0,0.0,2.0,1.0,0.0,13,4,25,17,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,,0.0,0.0,2,2,0.15,21.0,4,0.10,20,32.0,1.05,0.00,0.95,1.52,0.0,3.0

In [27]:
data2.isnull().sum()[data2.isnull().sum() > 0]

Series([], dtype: int64)

In [32]:
import pandas as pd
import io

extra = pd.read_excel('Análisis_de_Piso.xlsx', header=None, nrows=2)

print(extra.shape[1], data2.shape[1])  

extra.columns = data2.columns

resultado = pd.concat([extra, data2], ignore_index=True)

resultado.to_csv('Análisis_de_Piso_No_Nulos.csv', index=False)

51 51