In [79]:
# Importamos las librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [80]:
# Cargar el archivo 
data = pd.read_excel("SDC.xlsx")
data.head(20)

,Ventas,Unnamed: 1,12,7,8,13,6,21,17,17.1,...,38,30.2,41.1,41.2,35,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026,NaN,NaN
2,Generadas,5,6,11,23,26,43,55,36,56,...,85,74,95,82,32,519,1178,450,1697.0,0.392457
3,Aprobadas,1,2,7,14,8,13,30,19,26,...,41,42,44,35,12,215,451,201,666.0,0.509009
4,Condicionadas,0,0,1,0,4,0,3,0,1,...,14,16,17,10,9,100,287,102,387.0,NaN
5,Rechazadas,4,4,4,9,14,22,17,13,13,...,30,16,30,33,9,163,392,137,555.0,NaN
6,Formalizadas,1,1,5,11,3,6,17,9,7,...,18,16,19,13,4,105,234,91,339.0,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.482353,0.567568,0.463158,0.426829,0.375,0.414258,0.382852,0.446667,NaN,NaN
9,% de Formalizacion,1,0.5,0.714286,0.785714,0.375,0.461538,0.566667,0.473684,0.269231,...,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,N.º de solicitudes ingresadas por financiera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Financiera,0,0,0,0,0,0,0,0,51,...,85,74,95,82,32,TOTAL,% PARTICIPACION,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.063245,NaN,NaN,NaN
15,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,1,0.000518,NaN,NaN,NaN
16,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,121,0.062727,NaN,NaN,NaN
17,Banorte,-,-,-,-,-,-,-,-,1,...,33,33,34,15,10,790,0.409539,NaN,NaN,NaN
18,BBVA,-,-,-,-,-,-,-,-,12,...,12,7,11,16,3,202,0.104717,NaN,NaN,NaN
19,Ensueño,-,-,-,-,-,-,-,-,-,...,3,1,8,8,7,144,0.07465,NaN,NaN,NaN

In [81]:
#Lo ocupamos para revisar dimensiones
data.shape

(44, 37)

In [82]:
# Identificar los valores nulos por columna
valores_nulos = data.isnull().sum()
print(valores_nulos)
# Identificar los valores nulos totales
valores_nulos_total = data.isnull().sum().sum()
print("El número total de valores nulos es:", valores_nulos_total)

Ventas         10
Unnamed: 1     21
12             21
7              21
8              21
13             21
6              21
21             21
17             21
17.1           22
23             21
22             22
32             22
26             22
20             22
30             22
30.1           22
34             16
40             17
36             16
27             18
0              14
27.1           18
41             17
40.1           21
42             17
34.1           18
38             17
30.2           20
41.1           18
41.2           18
35             27
Unnamed: 32    11
Unnamed: 33    20
Unnamed: 34    36
Unnamed: 35    39
Unnamed: 36    42
dtype: int64
El número total de valores nulos es: 773

In [83]:
# Selecciono la tabla indicadores
indicadores = pd.read_excel(
    "SDC.xlsx",
    sheet_name="Hoja1",
    header=2,
    nrows=8,
    usecols="A:AI"
)

indicadores

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026
0,Generadas,5.0,6.000000,11.000000,23.000000,26.000000,43.000000,55.000000,36.000000,56.000000,...,113.000000,83.000000,85.000000,74.000000,95.000000,82.000000,32.000000,519.000000,1178.000000,450.000000
1,Aprobadas,1.0,2.000000,7.000000,14.000000,8.000000,13.000000,30.000000,19.000000,26.000000,...,37.000000,37.000000,41.000000,42.000000,44.000000,35.000000,12.000000,215.000000,451.000000,201.000000
2,Condicionadas,0.0,0.000000,1.000000,0.000000,4.000000,0.000000,3.000000,0.000000,1.000000,...,34.000000,21.000000,14.000000,16.000000,17.000000,10.000000,9.000000,100.000000,287.000000,102.000000
3,Rechazadas,4.0,4.000000,4.000000,9.000000,14.000000,22.000000,17.000000,13.000000,13.000000,...,36.000000,25.000000,30.000000,16.000000,30.000000,33.000000,9.000000,163.000000,392.000000,137.000000
4,Formalizadas,1.0,1.000000,5.000000,11.000000,3.000000,6.000000,17.000000,9.000000,7.000000,...,21.000000,17.000000,18.000000,16.000000,19.000000,13.000000,4.000000,105.000000,234.000000,91.000000
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.327434,0.445783,0.482353,0.567568,0.463158,0.426829,0.375000,0.414258,0.382852,0.446667
7,% de Formalizacion,1.0,0.500000,0.714286,0.785714,0.375000,0.461538,0.566667,0.473684,0.269231,...,0.567568,0.459459,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736

In [84]:
# Eliminar las filas vacías
indicadores = indicadores.dropna(how="all")
# Se restablecen los indices
indicadores = indicadores.reset_index(drop=True)

indicadores

,Indicador,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total 2024,Total 2025,Total 2026
0,Generadas,5.0,6.000000,11.000000,23.000000,26.000000,43.000000,55.000000,36.000000,56.000000,...,113.000000,83.000000,85.000000,74.000000,95.000000,82.000000,32.000000,519.000000,1178.000000,450.000000
1,Aprobadas,1.0,2.000000,7.000000,14.000000,8.000000,13.000000,30.000000,19.000000,26.000000,...,37.000000,37.000000,41.000000,42.000000,44.000000,35.000000,12.000000,215.000000,451.000000,201.000000
2,Condicionadas,0.0,0.000000,1.000000,0.000000,4.000000,0.000000,3.000000,0.000000,1.000000,...,34.000000,21.000000,14.000000,16.000000,17.000000,10.000000,9.000000,100.000000,287.000000,102.000000
3,Rechazadas,4.0,4.000000,4.000000,9.000000,14.000000,22.000000,17.000000,13.000000,13.000000,...,36.000000,25.000000,30.000000,16.000000,30.000000,33.000000,9.000000,163.000000,392.000000,137.000000
4,Formalizadas,1.0,1.000000,5.000000,11.000000,3.000000,6.000000,17.000000,9.000000,7.000000,...,21.000000,17.000000,18.000000,16.000000,19.000000,13.000000,4.000000,105.000000,234.000000,91.000000
5,% de Aprobación,0.2,0.333333,0.636364,0.608696,0.307692,0.302326,0.545455,0.527778,0.464286,...,0.327434,0.445783,0.482353,0.567568,0.463158,0.426829,0.375000,0.414258,0.382852,0.446667
6,% de Formalizacion,1.0,0.500000,0.714286,0.785714,0.375000,0.461538,0.566667,0.473684,0.269231,...,0.567568,0.459459,0.439024,0.380952,0.431818,0.371429,0.333333,0.488372,0.518847,0.452736

In [85]:
# Revisar nuevamente los valores nulos
print(indicadores.isnull().sum())

print(
    "Total de valores nulos:",
    indicadores.isnull().sum().sum()
)

Indicador          0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total 2024         0
Total 2025         0
Total 2026         0
dtype: int64
Total de valores nulos: 0

In [86]:
# Selecciono la tabla financiera
financieras = pd.read_excel(
    "SDC.xlsx",
    sheet_name="Hoja1",
    header=14,
    nrows=15,
    usecols="A:AH"
)


financieras

,Financiera,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,51,...,111,113,83.1,85,74,95,82,32,TOTAL,% PARTICIPACION
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.063245
1,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.000518
2,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,0.062727
3,Banorte,-,-,-,-,-,-,-,-,1,...,69,53.0,33.0,33.0,33.0,34.0,15.0,10.0,790.0,0.409539
4,BBVA,-,-,-,-,-,-,-,-,12,...,6,7.0,10.0,12.0,7.0,11.0,16.0,3.0,202.0,0.104717
5,Ensueño,-,-,-,-,-,-,-,-,-,...,22,9.0,4.0,3.0,1.0,8.0,8.0,7.0,144.0,0.074650
6,FinanMadrid,-,-,-,-,-,-,-,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.001037
7,INBURSA,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
8,MSTART,-,-,-,-,-,-,-,-,-,...,3,12.0,12.0,9.0,5.0,11.0,6.0,1.0,156.0,0.080871
9,Nexu,-,-,-,-,-,-,-,-,19,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,135.0,0.069984
10,Santander,-,-,-,-,-,-,-,-,1,...,11,26.0,18.0,25.0,21.0,18.0,30.0,7.0,442.0,0.229134
11,Scotiabank,-,-,-,-,-,-,-,-,-,...,NaN,3.0,2.0,1.0,3.0,9.0,6.0,4.0,41.0,0.021255
12,Sumafin,-,-,-,-,-,-,-,-,-,...,-,2.0,4.0,1.0,NaN,NaN,NaN,NaN,7.0,0.003629
13,Bajio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,0.000518
14,Kuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,4.0,1.0,NaN,9.0,0.004666

In [87]:
# Asignar correctamente los nombres de las columnas
financieras.columns = (
    ["Financiera"]
    + meses
    + ["TOTAL", "% PARTICIPACION"]
)

financieras

,Financiera,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Diciembre, 25.1","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",TOTAL,% PARTICIPACION
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.063245
1,ABC,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.000518
2,Afirme,-,-,-,-,-,-,-,-,18,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,121.0,0.062727
3,Banorte,-,-,-,-,-,-,-,-,1,...,69,53.0,33.0,33.0,33.0,34.0,15.0,10.0,790.0,0.409539
4,BBVA,-,-,-,-,-,-,-,-,12,...,6,7.0,10.0,12.0,7.0,11.0,16.0,3.0,202.0,0.104717
5,Ensueño,-,-,-,-,-,-,-,-,-,...,22,9.0,4.0,3.0,1.0,8.0,8.0,7.0,144.0,0.074650
6,FinanMadrid,-,-,-,-,-,-,-,-,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.001037
7,INBURSA,-,-,-,-,-,-,-,-,-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000
8,MSTART,-,-,-,-,-,-,-,-,-,...,3,12.0,12.0,9.0,5.0,11.0,6.0,1.0,156.0,0.080871
9,Nexu,-,-,-,-,-,-,-,-,19,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,135.0,0.069984
10,Santander,-,-,-,-,-,-,-,-,1,...,11,26.0,18.0,25.0,21.0,18.0,30.0,7.0,442.0,0.229134
11,Scotiabank,-,-,-,-,-,-,-,-,-,...,NaN,3.0,2.0,1.0,3.0,9.0,6.0,4.0,41.0,0.021255
12,Sumafin,-,-,-,-,-,-,-,-,-,...,-,2.0,4.0,1.0,NaN,NaN,NaN,NaN,7.0,0.003629
13,Bajio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,1.0,0.000518
14,Kuna,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,4.0,1.0,NaN,9.0,0.004666

In [88]:
# Revisar los valores nulos
print(financieras.isnull().sum())

print(
    "Total inicial de valores nulos:",
    financieras.isnull().sum().sum()
)

Financiera         1
Enero, 24          3
Febrero, 24        3
Marzo, 24          3
Abril, 24          3
Mayo, 24           3
Junio, 24          3
Julio, 24          3
Agosto, 24         3
Septiembre, 24     4
Octubre, 24        3
Noviembre, 24      4
Diciembre, 25      4
Enero, 25          4
Febrero, 25        4
Marzo, 25          4
Abril, 25          4
Mayo, 25           3
Junio, 25          6
Julio, 25          4
Agosto, 25         3
Septiembre, 25     3
Octubre, 25        7
Noviembre, 25      7
Diciembre, 25.1    9
Enero, 26          7
Febrero, 26        8
Marzo, 26          7
Abril, 26          8
Mayo,26            8
Junio, 26          8
Julio,26           9
TOTAL              1
% PARTICIPACION    0
dtype: int64
Total inicial de valores nulos: 154

In [89]:
# Sustituir guiones por 0
# Sustituir valores nulos por 0
financieras = financieras.replace("-", 0)
financieras = financieras.fillna(0)

financieras

,Financiera,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Diciembre, 25.1","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",TOTAL,% PARTICIPACION
0,0,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.063245
1,ABC,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000518
2,Afirme,0,0,0,0,0,0,0,0,18,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,121.0,0.062727
3,Banorte,0,0,0,0,0,0,0,0,1,...,69,53.0,33.0,33.0,33.0,34.0,15.0,10.0,790.0,0.409539
4,BBVA,0,0,0,0,0,0,0,0,12,...,6,7.0,10.0,12.0,7.0,11.0,16.0,3.0,202.0,0.104717
5,Ensueño,0,0,0,0,0,0,0,0,0,...,22,9.0,4.0,3.0,1.0,8.0,8.0,7.0,144.0,0.074650
6,FinanMadrid,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.001037
7,INBURSA,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000
8,MSTART,0,0,0,0,0,0,0,0,0,...,3,12.0,12.0,9.0,5.0,11.0,6.0,1.0,156.0,0.080871
9,Nexu,0,0,0,0,0,0,0,0,19,...,0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,135.0,0.069984
10,Santander,0,0,0,0,0,0,0,0,1,...,11,26.0,18.0,25.0,21.0,18.0,30.0,7.0,442.0,0.229134
11,Scotiabank,0,0,0,0,0,0,0,0,0,...,0,3.0,2.0,1.0,3.0,9.0,6.0,4.0,41.0,0.021255
12,Sumafin,0,0,0,0,0,0,0,0,0,...,0,2.0,4.0,1.0,0.0,0.0,0.0,0.0,7.0,0.003629
13,Bajio,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.000518
14,Kuna,0,0,0,0,0,0,0,0,0,...,0,0.0,0.0,0.0,4.0,4.0,1.0,0.0,9.0,0.004666

In [90]:
# Revisar nuevamente los valores nulos
print(financieras.isnull().sum())

print(
    "Total de valores nulos después del tratamiento:",
    financieras.isnull().sum().sum()
)

Financiera         0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
TOTAL              0
% PARTICIPACION    0
dtype: int64
Total de valores nulos después del tratamiento: 0

In [91]:
# Selecciono la tabla no autorizadas
no_autorizadas = pd.read_excel(
    "SDC.xlsx",
    sheet_name="Hoja1",
    header=32,
    nrows=4,
    usecols="A:AG"
)

#Agregar el nombre Motivo a la primera columna
no_autorizadas

no_autorizadas = no_autorizadas.rename(
    columns={no_autorizadas.columns[0]: "Motivo"}
)

no_autorizadas

,Motivo,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Noviembre, 25","Diciembre, 25.1","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total
0,Mal Buro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,26,27.0,33,19,15,12.0,12,22,NaN,311
1,Score bajo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,7.0,5,3,10,4.0,10,4,NaN,66
2,Capacidad de pago,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,NaN,0,2,3,NaN,6,6,NaN,17
3,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,NaN,0,1,2,NaN,1,1,NaN,7

In [92]:
#Revisar los resultados nulos totales y por parte

print(no_autorizadas.isnull().sum())

print(
    "Total inicial de valores nulos:",
    no_autorizadas.isnull().sum().sum()
)

Motivo             0
Enero, 24          4
Febrero, 24        4
Marzo, 24          4
Abril, 24          4
Mayo, 24           4
Junio, 24          4
Julio, 24          4
Agosto, 24         4
Septiembre, 24     4
Octubre, 24        4
Noviembre, 24      4
Diciembre, 25      4
Enero, 25          4
Febrero, 25        4
Marzo, 25          4
Abril, 25          4
Mayo, 25           2
Junio, 25          0
Julio, 25          1
Agosto, 25         2
Septiembre, 25     1
Octubre, 25        1
Noviembre, 25      0
Diciembre, 25.1    2
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          2
Mayo,26            0
Junio, 26          0
Julio,26           4
Total              0
dtype: int64
Total inicial de valores nulos: 79

In [93]:
#Sustituir valores nulos por 0
no_autorizadas = no_autorizadas.fillna(0)

In [94]:
#Revisar nuevamente los valores nulos
print(no_autorizadas.isnull().sum())

print(
    "Total de valores nulos:",
    no_autorizadas.isnull().sum().sum()
)

Motivo             0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total              0
dtype: int64
Total de valores nulos: 0

In [95]:
# Seleccionamos la tabla Motivos de SDC no formalizadas
no_formalizadas = pd.read_excel(
    "SDC.xlsx",
    sheet_name="Hoja1",
    header=40,
    nrows=4,
    usecols="A:AG"
)
#Agregar el nombre Motivo a la primera columna
no_formalizadas = no_formalizadas.rename(
    columns={no_formalizadas.columns[0]: "Motivo"}
)

no_formalizadas

,Motivo,"Enero, 24","Febrero, 24","Marzo, 24","Abril, 24","Mayo, 24","Junio, 24","Julio, 24","Agosto, 24","Septiembre, 24",...,"Noviembre, 25","Diciembre, 25.1","Enero, 26","Febrero, 26","Marzo, 26","Abril, 26","Mayo,26","Junio, 26","Julio,26",Total
0,Compra en otro lado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,6,0,4,1,1,2,2,2,NaN,44
1,Falta importe para enganche,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2,1,0,0,0,3,1,2,NaN,6
2,Espera comprar en futuro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,3,9,6,4,10,1,7,NaN,41
3,Otros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,3,0,5,11,3,9,5,NaN,41

In [96]:
#Revisar los valores nulos

print(no_formalizadas.isnull().sum())

print(
    "Total inicial de valores nulos:",
    no_formalizadas.isnull().sum().sum()
)

Motivo             0
Enero, 24          4
Febrero, 24        4
Marzo, 24          4
Abril, 24          4
Mayo, 24           4
Junio, 24          4
Julio, 24          4
Agosto, 24         4
Septiembre, 24     4
Octubre, 24        4
Noviembre, 24      4
Diciembre, 25      4
Enero, 25          4
Febrero, 25        4
Marzo, 25          4
Abril, 25          4
Mayo, 25           1
Junio, 25          1
Julio, 25          1
Agosto, 25         3
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           4
Total              0
dtype: int64
Total inicial de valores nulos: 74

In [97]:
# Sustituir valores nulos por 0

no_formalizadas = no_formalizadas.fillna(0)

In [98]:
#Revisar nuevamente los valores nulos
print(no_formalizadas.isnull().sum())

print(
    "Total de valores nulos:",
    no_formalizadas.isnull().sum().sum()
)

Motivo             0
Enero, 24          0
Febrero, 24        0
Marzo, 24          0
Abril, 24          0
Mayo, 24           0
Junio, 24          0
Julio, 24          0
Agosto, 24         0
Septiembre, 24     0
Octubre, 24        0
Noviembre, 24      0
Diciembre, 25      0
Enero, 25          0
Febrero, 25        0
Marzo, 25          0
Abril, 25          0
Mayo, 25           0
Junio, 25          0
Julio, 25          0
Agosto, 25         0
Septiembre, 25     0
Octubre, 25        0
Noviembre, 25      0
Diciembre, 25.1    0
Enero, 26          0
Febrero, 26        0
Marzo, 26          0
Abril, 26          0
Mayo,26            0
Junio, 26          0
Julio,26           0
Total              0
dtype: int64
Total de valores nulos: 0

In [99]:
# Guardar las tablas limpias en archivos CSV

indicadores.to_csv("SDC_Indicadores_Final.csv", index=False)

financieras.to_csv("SDC_Financieras_Final.csv", index=False)

no_autorizadas.to_csv("SDC_No_Autorizadas_Final.csv", index=False)

no_formalizadas.to_csv("SDC_No_Formalizadas_Final.csv", index=False)